services:
  tailscale-relay:
    ports:
      - "${PEER_RELAY_BIND_IP:?set PEER_RELAY_BIND_IP in .env}:${PEER_RELAY_PORT:?set PEER_RELAY_PORT in .env}:${PEER_RELAY_PORT:?set PEER_RELAY_PORT in .env}/udp"
    cap_add:
      - NET_ADMIN

  configure-peer-relay:
    command:
      - --socket=/var/run/tailscale/tailscaled.sock
      - set
      - --relay-server-port=${PEER_RELAY_PORT:?set PEER_RELAY_PORT in .env}
      - --relay-server-static-endpoints=${PEER_RELAY_PUBLIC_IP:?set PEER_RELAY_PUBLIC_IP in .env}:${PEER_RELAY_PORT:?set PEER_RELAY_PORT in .env}
